# Generated by Django 3.1.4 on 2020-12-29 16:49

from django.db import migrations, models
import django.db.models.deletion
import restaurants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('restaurant_id', models.AutoField(default=restaurants.models.random_id_genrate, primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('logo_img', models.FileField(blank=True, null=True, upload_to='restaurants/logos/')),
                ('cover_image', models.FileField(blank=True, null=True, upload_to='restaurants/cover_images/')),
                ('cuisines', models.TextField(max_length=255)),
                ('min_order_amt', models.FloatField()),
                ('foodmagic_pro', models.BooleanField(default=False)),
                ('Opening_time', models.DateTimeField()),
                ('closing_time', models.DateTimeField()),
                ('desc', models.TextField(max_length=255)),
                ('today_off', models.BooleanField(default=False)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_address', to='address.address')),
                ('seller_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.seller')),
            ],
        ),
    ]
