# Generated by Django 3.1.4 on 2020-12-29 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishRating',
            fields=[
                ('dish_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Dishes.dishes')),
                ('rating', models.IntegerField()),
                ('reviews', models.TextField(max_length=200)),
            ],
        ),
    ]
