# Generated by Django 3.1.4 on 2020-12-29 16:48

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(default=accounts.models.random_id_genrate, primary_key=True, serialize=False, unique=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='users_profiles/')),
                ('first_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('email_id', models.EmailField(max_length=255, unique=True, verbose_name='email_address')),
                ('is_seller', models.BooleanField(default=False)),
                ('is_deliveryBoy', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.AutoField(default=accounts.models.random_id_genrate, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('back_ac_number', models.CharField(blank=True, max_length=12, null=True)),
                ('ac_holder_name', models.CharField(max_length=55)),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Restaurant_seller', to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('Delivery_boy_id', models.AutoField(default=accounts.models.random_id_genrate, primary_key=True, serialize=False)),
                ('delivery_charge', models.FloatField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('customer_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_delivery_boy', to='accounts.customer')),
            ],
        ),
    ]
